
import json
import os
# import locale
# import configparser

# setting = configparser.ConfigParser()

# if os.path.exists(os.getenv('APPDATA') + '\\bfg_unpacker\\setting.ini'):
#     setting.read(os.getenv('APPDATA') + '\\bfg_unpacker\\setting.ini')
#     lang = setting['Main']['lang']
# else:
#     lang = locale.getdefaultlocale()[0].split('_')[0]

from source.setting import setting

lang = setting['Main']['lang']

script_dir = os.path.dirname(os.path.abspath(__file__)).replace(r"\source\ui", "").replace(r'\_internal', '')

if not os.path.exists(f'{script_dir}/data/local/{lang}.json'):
    lang = 'en'

with open(f'{script_dir}/data/local/{lang}.json', 'r', encoding='utf-8') as json_file:
    local = json.load(json_file)

with open(f'{script_dir}/data/local/en.json', 'r', encoding='utf-8') as json_file:
    eng = json.load(json_file)

lang_name = local.get('lang_name', eng['lang_name'])
lang_code = local.get('lang_code', eng['lang_code'])
all_games = local.get('all_games', eng['all_games'])
find = local.get('find', eng['find'])
all_caps = local.get('all_caps', eng['all_caps'])
fav_caps = local.get('fav_caps', eng['fav_caps'])
reimport = local.get('reimport', eng['reimport'])
show_console = local.get('show_console', eng['show_console'])
create_subfolders = local.get('create_subfolders', eng['create_subfolders'])
file = local.get('file', eng['file'])
unpack_with = local.get('unpack_with', eng['unpack_with'])
compress_formats = local.get('compress_formats', eng['compress_formats'])
find_formats = local.get('find_formats', eng['find_formats'])
additional = local.get('additional', eng['additional'])
consoles = local.get('consoles', eng['consoles'])
other = local.get('other', eng['other'])
archives = local.get('archives', eng['archives'])
game_engines = local.get('game_engines', eng['game_engines'])
disk_images = local.get('disk_images', eng['disk_images'])
installers = local.get('installers', eng['installers'])
convert = local.get('convert', eng['convert'])
video = local.get('video', eng['video'])
audio = local.get('audio', eng['audio'])
textures = local.get('textures', eng['textures'])
settings = local.get('settings', eng['settings'])
themes = local.get('themes', eng['themes'])
about = local.get('about', eng['about'])
quick_open = local.get('quick_open', eng['quick_open'])
leave = local.get('leave', eng['leave'])
language = local.get('language', eng['language'])
select_out_folder = local.get('select_out_folder', eng['select_out_folder'])
clear_out_folder = local.get('clear_out_folder', eng['clear_out_folder'])
make_out_folder = local.get('make_out_folder', eng['make_out_folder'])
autofind = local.get('autofind', eng['autofind'])
archive_scanner = local.get('archive_scanner', eng['archive_scanner'])
file_list = local.get('file_list', eng['file_list'])
create_theme = local.get('create_theme', eng['create_theme'])
select_something = local.get('select_something', eng['select_something'])
change_button = local.get('change_button', eng['change_button'])
cancel = local.get('cancel', eng['cancel'])
delete_to_trash = local.get('delete_to_trash', eng['delete_to_trash'])
full_delete = local.get('full_delete', eng['full_delete'])
show_on = local.get('show_on', eng['show_on'])
by_name = local.get('by_name', eng['by_name'])
by_years = local.get('by_years', eng['by_years'])
context_menu = local.get('context_menu', eng['context_menu'])
group_by = local.get('group_by', eng['group_by'])
out_folder = local.get('out_folder', eng['out_folder'])
apply = local.get('apply', eng['apply'])
save_theme = local.get('save_theme', eng['save_theme'])
primary_color = local.get('primary_color', eng['primary_color'])
primary_light = local.get('primary_light', eng['primary_light'])
second_color = local.get('second_color', eng['second_color'])
second_light = local.get('second_light', eng['second_light'])
second_dark = local.get('second_dark', eng['second_dark'])
font_color_1 = local.get('font_color_1', eng['font_color_1'])
font_color_2 = local.get('font_color_2', eng['font_color_2'])
enter_theme_name = local.get('enter_theme_name', eng['enter_theme_name'])
zoom = local.get('zoom', eng['zoom'])
select_folder = local.get('select_folder', eng['select_folder'])
open_file = local.get('open_file', eng['open_file'])
message = local.get('message', eng['message'])
successfully = local.get('successfully', eng['successfully'])
has_already_been = local.get('has_already_been', eng['has_already_been'])
not_correct_file = local.get('not_correct_file', eng['not_correct_file'])
done = local.get('done', eng['done'])
saving = local.get('saving', eng['saving'])
planet_added = local.get('planet_added', eng['planet_added'])
star_added = local.get('star_added', eng['star_added'])
exo_catalog = local.get('exo_catalog', eng['exo_catalog'])
data_about = local.get('data_about', eng['data_about'])
planets = local.get('planets', eng['planets'])
source = local.get('source', eng['source'])
make_with = local.get('make_with', eng['make_with'])
wait = local.get('wait', eng['wait'])
not_unzipped = local.get('not_unzipped', eng['not_unzipped'])
deleting = local.get('deleting', eng['deleting'])
unpacking = local.get('unpacking', eng['unpacking'])
creating = local.get('creating', eng['creating'])
work_in_progress = local.get('work_in_progress', eng['work_in_progress'])
empty_folder = local.get('empty_folder', eng['empty_folder'])
unsupported_platform = local.get('unsupported_platform', eng['unsupported_platform'])
disc_image = local.get('disc_image', eng['disc_image'])
classic_consoles = local.get('classic_consoles', eng['classic_consoles'])
error = local.get('error', eng['error'])
all_files = local.get('all_files', eng['all_files'])
quick_of = local.get('quick_of', eng['quick_of'])
open_qbms = local.get('open_qbms', eng['open_qbms'])
open_7z = local.get('open_7z', eng['open_7z'])
open_gaup = local.get('open_gaup', eng['open_gaup'])
open_inno = local.get('open_inno', eng['open_inno'])
convert_ffmpeg = local.get('convert_ffmpeg', eng['convert_ffmpeg'])
convert_bink = local.get('convert_bink', eng['convert_bink'])
convert_wwise = local.get('convert_wwise', eng['convert_wwise'])
convert_pillow = local.get('convert_pillow', eng['convert_pillow'])
unpack_unreal = local.get('unpack_unreal', eng['unpack_unreal'])
unpack_unity = local.get('unpack_unity', eng['unpack_unity'])
unpack_idtech = local.get('unpack_idtech', eng['unpack_idtech'])
unpack_source = local.get('unpack_source', eng['unpack_source'])
unpack_creation = local.get('unpack_creation', eng['unpack_creation'])
unpack_cry = local.get('unpack_cry', eng['unpack_cry'])
unpack_red = local.get('unpack_red', eng['unpack_red'])
unpack_godot = local.get('unpack_godot', eng['unpack_godot'])
unpack_rpgmaker = local.get('unpack_rpgmaker', eng['unpack_rpgmaker'])
unpack_renpy = local.get('unpack_renpy', eng['unpack_renpy'])
unpack_unigen = local.get('unpack_unigen', eng['unpack_unigen'])
ps_audio_tool = local.get('ps_audio_tool', eng['ps_audio_tool'])
header_dds = local.get('header_dds', eng['header_dds'])
header_atrac = local.get('header_atrac', eng['header_atrac'])
header_wav = local.get('header_wav', eng['header_wav'])
run_setting = local.get('run_setting', eng['run_setting'])
empty_of = local.get('empty_of', eng['empty_of'])
alphabet = local.get('alphabet', eng['alphabet'])
close = local.get('close', eng['close'])
find_zip_method = local.get('find_zip_method', eng['find_zip_method'])
zip_method = local.get('zip_method', eng['zip_method'])
yes = local.get('yes', eng['yes'])
no = local.get('no', eng['no'])
load_bar = local.get('load_bar', eng['load_bar'])
compress = local.get('compress', eng['compress'])
duration = local.get('duration', eng['duration'])
test_algorythm = local.get('test_algorythm', eng['test_algorythm'])
dump_create = local.get('dump_create', eng['dump_create'])
filed_to_unzip = local.get('filed_to_unzip', eng['filed_to_unzip'])
testing = local.get('testing', eng['testing'])
fav_image_format = local.get('fav_image_format', eng['fav_image_format'])
image_action = local.get('image_action', eng['image_action'])
only_original = local.get('only_original', eng['only_original'])
only_convert = local.get('only_convert', eng['only_convert'])
original_convert = local.get('original_convert', eng['original_convert'])
six_files_in_fol = local.get('six_files_in_fol', eng['six_files_in_fol'])
one_format = local.get('one_format', eng['one_format'])
one_param = local.get('one_param', eng['one_param'])
eof_data = local.get('eof_data', eng['eof_data'])
info = local.get('INFO', eng['INFO'])
INFO = local.get('INFO', eng['INFO'])
error_in_file = local.get('error_in_file', eng['error_in_file'])
invalid_version = local.get('invalid_version', eng['invalid_version'])
do_not_exist = local.get('do_not_exist', eng['do_not_exist'])
wrong_ue4 = local.get('wrong_ue4', eng['wrong_ue4'])
almost_done = local.get('almost_done', eng['almost_done'])
files_is_moving = local.get('files_is_moving', eng['files_is_moving'])
is_process = local.get('is_process', eng['is_process'])
run_as_admin = local.get('run_as_admin', eng['run_as_admin'])
could_not_delete = local.get('could_not_delete', eng['could_not_delete'])
not_find_unpacker = local.get('not_find_unpacker', eng['not_find_unpacker'])
file_type = local.get('file_type', eng['file_type'])
tf_selector = local.get('tf_selector', eng['tf_selector'])
hand_select = local.get('hand_select', eng['hand_select'])
enter_value = local.get('enter_value', eng['enter_value'])
multivol = local.get('multivol', eng['multivol'])
big_image_error = local.get('big_image_error', eng['big_image_error'])
oodle_version = local.get('oodle_version', eng['oodle_version'])
unsupported_ftype = local.get('unsupported_ftype', eng['unsupported_ftype'])
offset = local.get('offset', eng['offset'])
clear = local.get('clear', eng['clear'])
create = local.get('create', eng['create'])
six_images = local.get('six_images', eng['six_images'])
delete = local.get('delete', eng['delete'])
already_6 = local.get('already_6', eng['already_6'])
warning = local.get('warning', eng['warning'])
