
from PyQt5.QtCore import QRect, QCoreApplication, QMetaObject
from PyQt5.QtWidgets import *
import source.ui.localize as TL


class Ui_BFGUnpacker:

    def __init__(self):
        self.centralwidget = QWidget(self)
        self.comboBox_gameList = QComboBox(self.centralwidget)
        self.comboBox_gameList.setGeometry(QRect(80, 40, 375, 30))
        self.toolButton_plus = QToolButton(self.centralwidget)
        self.toolButton_plus.setGeometry(QRect(455, 40, 30, 30))
        self.toolButton_minus = QToolButton(self.centralwidget)
        self.toolButton_minus.setGeometry(QRect(485, 40, 30, 30))
        self.logWindow = QTextBrowser(self.centralwidget)
        self.logWindow.setGeometry(QRect(300, 79, 295, 520))
        self.all_games_label = QLabel(self.centralwidget)
        self.all_games_label.setGeometry(QRect(490, 605, 100, 15))
        self.gameList_treeView = QTreeView(self.centralwidget)
        self.gameList_treeView.setGeometry(QRect(0, 79, 295, 520))
        self.toolButton_Find = QToolButton(self.centralwidget)
        self.toolButton_Find.setGeometry(QRect(515, 40, 85, 30))
        self.btn_All_Favorite = QToolButton(self.centralwidget)
        self.btn_All_Favorite.setGeometry(QRect(0, 40, 80, 30))
        self.checkBox_Reimport = QCheckBox(self.centralwidget)
        self.checkBox_Reimport.setGeometry(QRect(10, 600, 100, 20))
        self.checkBox_ShowConsole = QCheckBox(self.centralwidget)
        self.checkBox_ShowConsole.setGeometry(QRect(100, 600, 140, 20))
        self.checkBox_createSubfolders = QCheckBox(self.centralwidget)
        self.checkBox_createSubfolders.setGeometry(QRect(250, 600, 150, 20))
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QRect(0, 0, 600, 40))
        self.upperButtons = QHBoxLayout(self.layoutWidget)
        self.upperButtons.setContentsMargins(0, 0, 0, 0)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(self)
        self.menubar.setGeometry(QRect(0, 0, 600, 20))
        self.menu = QMenu(self.menubar)
        self.unpackWith = QMenu(self.menu)
        self.zippedFormats = QMenu(self.menu)
        self.formatSearch = QMenu(self.menu)
        self.additionalMenu = QMenu(self.menu)
        self.consolesMenu = QMenu(self.menu)
        self.menuSony = QMenu(self.consolesMenu)
        self.menuPlayStation_1 = QMenu(self.menuSony)
        self.menuPlayStation_2 = QMenu(self.menuSony)
        self.menuPlayStation_3 = QMenu(self.menuSony)
        self.menuPlayStation_4 = QMenu(self.menuSony)
        self.menuPlayStation_5 = QMenu(self.menuSony)
        self.menuPSP = QMenu(self.menuSony)
        self.menuPlayStation_Vita = QMenu(self.menuSony)
        self.menuMicrosoft = QMenu(self.consolesMenu)
        self.menuXBox_Classic = QMenu(self.menuMicrosoft)
        self.menuXBox_One = QMenu(self.menuMicrosoft)
        self.menuXBox_Series = QMenu(self.menuMicrosoft)
        self.menuNintendo = QMenu(self.consolesMenu)
        self.menuGameCube = QMenu(self.menuNintendo)
        self.menuWii = QMenu(self.menuNintendo)
        self.menuWii_U = QMenu(self.menuNintendo)
        self.menuSwitch = QMenu(self.menuNintendo)
        self.menuClassic_Consoles = QMenu(self.menuNintendo)
        self.menuSega = QMenu(self.consolesMenu)
        self.menuDreamcast = QMenu(self.menuSega)
        self.menuMegaDrive = QMenu(self.menuSega)
        self.menuSaturn = QMenu(self.menuSega)
        self.menuSegaOther = QMenu(self.menuSega)
        self.menuOtherConsoles = QMenu(self.consolesMenu)
        self.menu_5 = QMenu(self.menu)
        self.menu_6 = QMenu(self.menu)
        self.menu_7 = QMenu(self.menu)
        self.menu_8 = QMenu(self.menu)
        self.menu_2 = QMenu(self.menubar)
        self.videoConverters = QMenu(self.menu_2)
        self.audioConverters = QMenu(self.menu_2)
        self.imageConverters = QMenu(self.menu_2)
        self.menu_3 = QMenu(self.menubar)
        self.themes_list_2 = QMenu(self.menu_3)
        self.menu_4 = QMenu(self.menubar)
        self.setMenuBar(self.menubar)
        self.quickOpen = QAction(self)
        self.exitAction = QAction(self)
        self.action_Language = QAction(self)
        self.action_SelectOutPath = QAction(self)
        self.action_ClearOutPath = QAction(self)
        self.action_CreateOutPath = QAction(self)
        self.action_Settings = QAction(self)
        self.action_DeleteEmptyFiles = QAction(self)
        self.action_DeleteEmptySubfolders = QAction(self)
        self.action_About = QAction(self)
        self.action7z_Archiver = QAction(self)
        self.actionGame_Archive_Unpacker_Plugin = QAction(self)
        self.actionTotal_Observer = QAction(self)
        self.actionSprite_and_Archive_Utility = QAction(self)
        self.action0_9 = QAction(self)
        self.actionA = QAction(self)
        self.actionB = QAction(self)
        self.actionC = QAction(self)
        self.actionD = QAction(self)
        self.actionE = QAction(self)
        self.actionF = QAction(self)
        self.actionG = QAction(self)
        self.actionH = QAction(self)
        self.actionI = QAction(self)
        self.actionJ = QAction(self)
        self.actionK = QAction(self)
        self.actionL = QAction(self)
        self.actionM = QAction(self)
        self.actionN = QAction(self)
        self.actionO = QAction(self)
        self.actionP = QAction(self)
        self.actionQ = QAction(self)
        self.actionR = QAction(self)
        self.actionS = QAction(self)
        self.actionT = QAction(self)
        self.actionU = QAction(self)
        self.actionV = QAction(self)
        self.actionW = QAction(self)
        self.actionX = QAction(self)
        self.actionY = QAction(self)
        self.actionZ = QAction(self)
        self.actionZlib_Deflate = QAction(self)
        self.actionLZ4 = QAction(self)
        self.actionWAV = QAction(self)
        self.autoSearchScripts = QAction(self)
        self.actionFileList = QAction(self)
        self.actionArchiveScanner = QAction(self)
        self.actionFFMPEG_Video_Converter = QAction(self)
        self.actionRad_Video_Tools = QAction(self)
        self.actionMedia_Info = QAction(self)
        self.actionFFMPEG_Sound_Converter = QAction(self)
        self.actionVGM_Stream_Tools = QAction(self)
        self.actionFSBext = QAction(self)
        self.actionToWAV = QAction(self)
        self.actionRAW_to_WAV = QAction(self)
        self.actionRAW_to_Atrac = QAction(self)
        self.actionPlayStation_Audio_Converter = QAction(self)
        self.actionXWM_WAV_Audio_Converter = QAction(self)
        self.actionFFMPEG_Image_Converter = QAction(self)
        self.actionSAU = QAction(self)
        self.actionnConvert = QAction(self)
        self.actionImage_to_DDS_Microsoft = QAction(self)
        self.actionImage_to_DDS_nVidia = QAction(self)
        self.actionDDS_Header_Generator = QAction(self)
        self.actionCubeMap_Creator = QAction(self)
        self.actionICO_Icon_Splitter = QAction(self)
        self.create_theme = QAction(self)
        self.unpackWith.addAction(self.action7z_Archiver)
        self.unpackWith.addAction(self.actionGame_Archive_Unpacker_Plugin)
        self.unpackWith.addAction(self.actionTotal_Observer)
        self.unpackWith.addAction(self.actionSprite_and_Archive_Utility)
        self.zippedFormats.addAction(self.actionZlib_Deflate)
        self.zippedFormats.addAction(self.actionLZ4)
        self.formatSearch.addAction(self.actionWAV)
        self.additionalMenu.addAction(self.autoSearchScripts)
        self.additionalMenu.addAction(self.actionArchiveScanner)
        self.additionalMenu.addAction(self.actionFileList)
        self.menuSony.addAction(self.menuPlayStation_1.menuAction())
        self.menuSony.addAction(self.menuPlayStation_2.menuAction())
        self.menuSony.addAction(self.menuPlayStation_3.menuAction())
        self.menuSony.addAction(self.menuPlayStation_4.menuAction())
        self.menuSony.addAction(self.menuPlayStation_5.menuAction())
        self.menuSony.addAction(self.menuPSP.menuAction())
        self.menuSony.addAction(self.menuPlayStation_Vita.menuAction())
        self.menuMicrosoft.addAction(self.menuXBox_Classic.menuAction())
        self.menuMicrosoft.addAction(self.menuXBox_One.menuAction())
        self.menuMicrosoft.addAction(self.menuXBox_Series.menuAction())
        self.menuNintendo.addAction(self.menuGameCube.menuAction())
        self.menuNintendo.addAction(self.menuWii.menuAction())
        self.menuNintendo.addAction(self.menuWii_U.menuAction())
        self.menuNintendo.addAction(self.menuSwitch.menuAction())
        self.menuNintendo.addAction(self.menuClassic_Consoles.menuAction())
        self.menuSega.addAction(self.menuDreamcast.menuAction())
        self.menuSega.addAction(self.menuMegaDrive.menuAction())
        self.menuSega.addAction(self.menuSaturn.menuAction())
        self.menuSega.addAction(self.menuSegaOther.menuAction())
        self.consolesMenu.addAction(self.menuSony.menuAction())
        self.consolesMenu.addAction(self.menuMicrosoft.menuAction())
        self.consolesMenu.addAction(self.menuNintendo.menuAction())
        self.consolesMenu.addAction(self.menuSega.menuAction())
        self.consolesMenu.addAction(self.menuOtherConsoles.menuAction())
        self.menu.addAction(self.quickOpen)
        self.menu.addAction(self.unpackWith.menuAction())
        self.menu.addAction(self.menu_5.menuAction())
        self.menu.addAction(self.menu_6.menuAction())
        self.menu.addAction(self.consolesMenu.menuAction())
        self.menu.addAction(self.menu_7.menuAction())
        self.menu.addAction(self.menu_8.menuAction())
        self.menu.addAction(self.zippedFormats.menuAction())
        self.menu.addAction(self.formatSearch.menuAction())
        self.menu.addAction(self.additionalMenu.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.exitAction)
        self.videoConverters.addAction(self.actionFFMPEG_Video_Converter)
        self.videoConverters.addAction(self.actionRad_Video_Tools)
        self.videoConverters.addAction(self.actionMedia_Info)
        self.audioConverters.addAction(self.actionFFMPEG_Sound_Converter)
        self.audioConverters.addAction(self.actionVGM_Stream_Tools)
        self.audioConverters.addAction(self.actionFSBext)
        self.audioConverters.addAction(self.actionToWAV)
        self.audioConverters.addAction(self.actionRAW_to_WAV)
        self.audioConverters.addAction(self.actionRAW_to_Atrac)
        self.audioConverters.addAction(self.actionPlayStation_Audio_Converter)
        self.audioConverters.addAction(self.actionXWM_WAV_Audio_Converter)
        self.imageConverters.addAction(self.actionFFMPEG_Image_Converter)
        self.imageConverters.addAction(self.actionSAU)
        self.imageConverters.addAction(self.actionnConvert)
        self.imageConverters.addAction(self.actionImage_to_DDS_Microsoft)
        self.imageConverters.addAction(self.actionImage_to_DDS_nVidia)
        self.imageConverters.addAction(self.actionDDS_Header_Generator)
        self.imageConverters.addAction(self.actionCubeMap_Creator)
        self.imageConverters.addAction(self.actionICO_Icon_Splitter)
        self.menu_2.addAction(self.videoConverters.menuAction())
        self.menu_2.addAction(self.audioConverters.menuAction())
        self.menu_2.addAction(self.imageConverters.menuAction())
        self.menu_3.addAction(self.action_Language)
        self.menu_3.addAction(self.themes_list_2.menuAction())
        self.menu_3.addAction(self.create_theme)
        self.menu_3.addAction(self.action_Settings)
        self.menu_3.addAction(self.action_SelectOutPath)
        self.menu_3.addAction(self.action_ClearOutPath)
        self.menu_3.addAction(self.action_CreateOutPath)
        self.menu_3.addAction(self.action_DeleteEmptyFiles)
        self.menu_3.addAction(self.action_DeleteEmptySubfolders)
        self.menu_4.addAction(self.action_About)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi()
        QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QCoreApplication.translate
        self.toolButton_plus.setText(_translate("BFGUnpacker", "+"))
        self.toolButton_minus.setText(_translate("BFGUnpacker", "-"))
        self.all_games_label.setText(_translate("BFGUnpacker", TL.all_games))
        self.toolButton_Find.setText(_translate("BFGUnpacker", TL.find))
        self.btn_All_Favorite.setText(_translate("BFGUnpacker", TL.all_caps))
        self.checkBox_Reimport.setText(_translate("BFGUnpacker", TL.reimport))
        self.checkBox_ShowConsole.setText(_translate("BFGUnpacker", TL.show_console))
        self.checkBox_createSubfolders.setText(_translate("BFGUnpacker", TL.create_subfolders))
        self.menu.setTitle(_translate("BFGUnpacker", TL.file))
        self.unpackWith.setTitle(_translate("BFGUnpacker", TL.unpack_with))
        self.zippedFormats.setTitle(_translate("BFGUnpacker", TL.compress_formats))
        self.formatSearch.setTitle(_translate("BFGUnpacker", TL.find_formats))
        self.additionalMenu.setTitle(_translate("BFGUnpacker", TL.additional))
        self.consolesMenu.setTitle(_translate("BFGUnpacker", TL.consoles))
        self.menuSony.setTitle(_translate("BFGUnpacker", "Sony"))
        self.menuPlayStation_1.setTitle(_translate("BFGUnpacker", "PlayStation 1"))
        self.menuPlayStation_2.setTitle(_translate("BFGUnpacker", "PlayStation 2"))
        self.menuPlayStation_3.setTitle(_translate("BFGUnpacker", "PlayStation 3"))
        self.menuPlayStation_4.setTitle(_translate("BFGUnpacker", "PlayStation 4"))
        self.menuPlayStation_5.setTitle(_translate("BFGUnpacker", "PlayStation 5"))
        self.menuPSP.setTitle(_translate("BFGUnpacker", "PSP"))
        self.menuPlayStation_Vita.setTitle(_translate("BFGUnpacker", "PlayStation Vita"))
        self.menuMicrosoft.setTitle(_translate("BFGUnpacker", "Microsoft"))
        self.menuXBox_Classic.setTitle(_translate("BFGUnpacker", "XBox Classic"))
        self.menuXBox_One.setTitle(_translate("BFGUnpacker", "XBox One"))
        self.menuXBox_Series.setTitle(_translate("BFGUnpacker", "XBox Series"))
        self.menuNintendo.setTitle(_translate("BFGUnpacker", "Nintendo"))
        self.menuGameCube.setTitle(_translate("BFGUnpacker", "GameCube"))
        self.menuWii.setTitle(_translate("BFGUnpacker", "Wii"))
        self.menuWii_U.setTitle(_translate("BFGUnpacker", "Wii U"))
        self.menuSwitch.setTitle(_translate("BFGUnpacker", "Switch"))
        self.menuClassic_Consoles.setTitle(_translate("BFGUnpacker", "Classic Consoles"))
        self.menuSega.setTitle(_translate("BFGUnpacker", "Sega"))
        self.menuDreamcast.setTitle(_translate("BFGUnpacker", "Dreamcast"))
        self.menuMegaDrive.setTitle(_translate("BFGUnpacker", "MegaDrive"))
        self.menuSaturn.setTitle(_translate("BFGUnpacker", "Saturn"))
        self.menuSegaOther.setTitle(_translate("BFGUnpacker", TL.other))
        self.menuOtherConsoles.setTitle(_translate("BFGUnpacker", TL.other))
        self.menu_5.setTitle(_translate("BFGUnpacker", TL.archives))
        self.menu_6.setTitle(_translate("BFGUnpacker", TL.game_engines))
        self.menu_7.setTitle(_translate("BFGUnpacker", TL.disk_images))
        self.menu_8.setTitle(_translate("BFGUnpacker", TL.installers))
        self.menu_2.setTitle(_translate("BFGUnpacker", TL.convert))
        self.videoConverters.setTitle(_translate("BFGUnpacker", TL.video))
        self.audioConverters.setTitle(_translate("BFGUnpacker", TL.audio))
        self.imageConverters.setTitle(_translate("BFGUnpacker", TL.textures))
        self.menu_3.setTitle(_translate("BFGUnpacker", TL.settings))
        self.themes_list_2.setTitle(_translate("BFGUnpacker", TL.themes))
        self.menu_4.setTitle(_translate("BFGUnpacker", TL.about))
        self.quickOpen.setText(_translate("BFGUnpacker", TL.quick_open))
        self.exitAction.setText(_translate("BFGUnpacker", TL.leave))
        self.action_Language.setText(_translate("BFGUnpacker", TL.language))
        self.action_SelectOutPath.setText(_translate("BFGUnpacker", TL.select_out_folder))
        self.action_ClearOutPath.setText(_translate("BFGUnpacker", TL.clear_out_folder))
        self.action_CreateOutPath.setText(_translate("BFGUnpacker", TL.make_out_folder))
        self.action_Settings.setText(_translate("BFGUnpacker", TL.settings))
        self.action_DeleteEmptyFiles.setText(_translate("BFGUnpacker", TL.delete_empty_files))
        self.action_DeleteEmptySubfolders.setText(_translate("BFGUnpacker", TL.delete_empty_subfolders))
        self.action_About.setText(_translate("BFGUnpacker", TL.about))
        self.action7z_Archiver.setText(_translate("BFGUnpacker", "7z Archiver"))
        self.actionGame_Archive_Unpacker_Plugin.setText(_translate("BFGUnpacker", "Game Archive Unpacker Plugin"))
        self.actionTotal_Observer.setText(_translate("BFGUnpacker", "Total Observer"))
        self.actionSprite_and_Archive_Utility.setText(_translate("BFGUnpacker", "Sprite and Archive Utility"))
        self.action0_9.setText(_translate("BFGUnpacker", "0-9"))
        self.actionA.setText(_translate("BFGUnpacker", "A"))
        self.actionB.setText(_translate("BFGUnpacker", "B"))
        self.actionC.setText(_translate("BFGUnpacker", "C"))
        self.actionD.setText(_translate("BFGUnpacker", "D"))
        self.actionE.setText(_translate("BFGUnpacker", "E"))
        self.actionF.setText(_translate("BFGUnpacker", "F"))
        self.actionG.setText(_translate("BFGUnpacker", "G"))
        self.actionH.setText(_translate("BFGUnpacker", "H"))
        self.actionI.setText(_translate("BFGUnpacker", "I"))
        self.actionJ.setText(_translate("BFGUnpacker", "J"))
        self.actionK.setText(_translate("BFGUnpacker", "K"))
        self.actionL.setText(_translate("BFGUnpacker", "L"))
        self.actionM.setText(_translate("BFGUnpacker", "M"))
        self.actionN.setText(_translate("BFGUnpacker", "N"))
        self.actionO.setText(_translate("BFGUnpacker", "O"))
        self.actionP.setText(_translate("BFGUnpacker", "P"))
        self.actionQ.setText(_translate("BFGUnpacker", "Q"))
        self.actionR.setText(_translate("BFGUnpacker", "R"))
        self.actionS.setText(_translate("BFGUnpacker", "S"))
        self.actionT.setText(_translate("BFGUnpacker", "T"))
        self.actionU.setText(_translate("BFGUnpacker", "U"))
        self.actionV.setText(_translate("BFGUnpacker", "V"))
        self.actionW.setText(_translate("BFGUnpacker", "W"))
        self.actionX.setText(_translate("BFGUnpacker", "X"))
        self.actionY.setText(_translate("BFGUnpacker", "Y"))
        self.actionZ.setText(_translate("BFGUnpacker", "Z"))
        self.actionZlib_Deflate.setText(_translate("BFGUnpacker", "Zlib, Deflate"))
        self.actionLZ4.setText(_translate("BFGUnpacker", "LZ4"))
        self.actionWAV.setText(_translate("BFGUnpacker", "WAV"))
        self.autoSearchScripts.setText(_translate("BFGUnpacker", TL.autofind))
        self.actionFileList.setText(_translate("BFGUnpacker", TL.file_list))
        self.actionArchiveScanner.setText(_translate("BFGUnpacker", TL.archive_scanner))
        self.actionFFMPEG_Video_Converter.setText(_translate("BFGUnpacker", "FFMPEG Video Converter"))
        self.actionRad_Video_Tools.setText(_translate("BFGUnpacker", "Rad Video Tools"))
        self.actionMedia_Info.setText(_translate("BFGUnpacker", "Media Info"))
        self.actionFFMPEG_Sound_Converter.setText(_translate("BFGUnpacker", "FFMPEG Sound Converter"))
        self.actionVGM_Stream_Tools.setText(_translate("BFGUnpacker", "VGM Stream Tools"))
        self.actionFSBext.setText(_translate("BFGUnpacker", "FSBext "))
        self.actionToWAV.setText(_translate("BFGUnpacker", "ToWAV"))
        self.actionRAW_to_WAV.setText(_translate("BFGUnpacker", "RAW to WAV"))
        self.actionRAW_to_Atrac.setText(_translate("BFGUnpacker", "RAW to Atrac"))
        self.actionPlayStation_Audio_Converter.setText(_translate("BFGUnpacker", "PlayStation Audio Converter"))
        self.actionXWM_WAV_Audio_Converter.setText(_translate("BFGUnpacker", "XWM\\WAV Audio Converter"))
        self.actionFFMPEG_Image_Converter.setText(_translate("BFGUnpacker", "FFMPEG Image Converter"))
        self.actionSAU.setText(_translate("BFGUnpacker", "SAU"))
        self.actionnConvert.setText(_translate("BFGUnpacker", "nConvert"))
        self.actionImage_to_DDS_Microsoft.setText(_translate("BFGUnpacker", "Image to DDS (Microsoft)"))
        self.actionImage_to_DDS_nVidia.setText(_translate("BFGUnpacker", "Image to DDS (nVidia)"))
        self.actionDDS_Header_Generator.setText(_translate("BFGUnpacker", "DDS Header Generator"))
        self.actionCubeMap_Creator.setText(_translate("BFGUnpacker", "CubeMap Creator"))
        self.actionICO_Icon_Splitter.setText(_translate("BFGUnpacker", "ICO Icon Splitter"))
        self.create_theme.setText(_translate("BFGUnpacker", TL.create_theme))
